# Generated by Django 5.2.4 on 2026-07-29 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="Institution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                (
                    "layer",
                    models.CharField(
                        choices=[
                            ("decision", "Decision Institution"),
                            ("influence", "Influence Network"),
                            ("implementation", "Implementation System"),
                        ],
                        max_length=30,
                    ),
                ),
                ("description", models.TextField()),
                (
                    "authority",
                    models.PositiveIntegerField(
                        default=50,
                        help_text="Relative institutional authority from 0 to 100.",
                    ),
                ),
                (
                    "capacity",
                    models.PositiveIntegerField(
                        default=50,
                        help_text="Relative implementation capacity from 0 to 100.",
                    ),
                ),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="institutions",
                        to="country.country",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Policy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150)),
                ("public_description", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("proposed", "Proposed"),
                            ("processed", "Processed"),
                            ("authorized", "Authorized"),
                            ("implemented", "Implemented"),
                        ],
                        default="proposed",
                        max_length=30,
                    ),
                ),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="policies",
                        to="country.country",
                    ),
                ),
                (
                    "decision_institution",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="authorized_policies",
                        to="country.institution",
                    ),
                ),
                (
                    "implementation_institution",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="implemented_policies",
                        to="country.institution",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InfluenceConnection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("influence_type", models.CharField(max_length=100)),
                (
                    "influence_strength",
                    models.PositiveIntegerField(
                        default=50, help_text="Relative influence from 0 to 100."
                    ),
                ),
                ("explanation", models.TextField(blank=True)),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="influence_connections",
                        to="country.institution",
                    ),
                ),
                (
                    "policy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="influences",
                        to="country.policy",
                    ),
                ),
            ],
        ),
    ]
